ppw4/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
]

ppw5/urls.py
from django.urls import path
from .views import *

app_name = 'ppw5'
urlpatterns = [
    path('schedule/', schedule, name='schedule'),
    path('post/', activity_post, name='activity_post'),
    path('activity/', activity, name='activity'),
    path('activity/empty', delete, name='empty')
]

story_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('landingpage.urls')),
    path('admin/', admin.site.urls),
    path('ppw4/', include('ppw4.urls')),
    path('ppw5/', include(('ppw5.urls', 'ppw5'), namespace='ppw5')),
    path('ppw6/', include(('ppw6.urls', 'ppw6'), namespace='ppw6')),
    path('ppw8/', include(('ppw8.urls', 'ppw8'), namespace='ppw8')),
    path('ppw9/', include(('ppw9.urls', 'ppw9'), namespace='ppw9')),
    path('landingpage/', include(('landingpage.urls', 'landingpage'), namespace='landingpage')),
    path('ppw10/', include(('ppw10.urls', 'ppw10'), namespace='ppw10')),
    path('auth/', include('social_django.urls', namespace ='social')),
]

ppw5/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class JadwalPribadi(models.Model):
    date_time = models.DateField(default = timezone.now)
    activity_name = models.CharField(max_length = 200)
    place_name = models.CharField(max_length = 50)
    time = models.TimeField()

    AKADEMIS = 'Akademis'
    KEPANITIAAN ='Kepanitiaan dan Organisasi'
    KELUARGA = 'Keluarga'
    OLAHRAGA = 'Olahraga'
    MAIN = 'Main'
    OTHER = 'Other'
    CATEGORY_CHOICES = (
        (AKADEMIS, 'Akademis'),
        (KEPANITIAAN, 'Kepanitiaan dan Organisasi'),
        (KELUARGA, 'Keluarga'),
        (OLAHRAGA, 'Olahraga'),
        (MAIN, 'Main'),
        (OTHER, 'Other'),
    )

    category_name = models.CharField(max_length = 70, choices = CATEGORY_CHOICES, default = AKADEMIS)

ppw5/forms.py
from django import forms

class Activity_Form(forms.Form):
    AKADEMIS = 'Akademis'
    KEPANITIAAN ='Kepanitiaan dan Organisasi'
    KELUARGA = 'Keluarga'
    OLAHRAGA = 'Olahraga'
    MAIN = 'Main'
    OTHER = 'Other'
    CATEGORY_CHOICES = (
        (AKADEMIS, 'Akademis'),
        (KEPANITIAAN, 'Kepanitiaan dan Organisasi'),
        (KELUARGA, 'Keluarga'),
        (OLAHRAGA, 'Olahraga'),
        (MAIN, 'Main'),
        (OTHER, 'Other'),
    )
    attrs = {
        'class': 'form-control'
    }

    date_time = forms.DateField(label = '', required=True, widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.TimeField(label = '', required=True, widget=forms.TimeInput(attrs={'type': 'time'}))
    activity_name = forms.CharField(label = '', max_length = 200, required=True, widget=forms.TextInput(attrs=attrs))
    place_name = forms.CharField(label = '', max_length = 50, required=True, widget=forms.TextInput(attrs=attrs))
    category_name = forms.CharField(max_length = 70, label = '', required=True, widget = forms.Select(choices = CATEGORY_CHOICES))

ppw5/views.py
from django.shortcuts import render
from .forms import Activity_Form
from .models import JadwalPribadi
from django.http import HttpResponseRedirect

# Create your views here.

def activity_post(request):
    response = {}
    form = Activity_Form(request.POST or None)
    print(form.errors)
    if(request.method == 'POST' and form.is_valid()):
        response['date_time'] = request.POST['date_time']
        response['time'] = request.POST['time']
        response['activity_name'] = request.POST['activity_name']
        response['place_name'] = request.POST['place_name']
        response['category_name'] = request.POST['category_name']
        print(request.POST["date_time"])
        formdone = JadwalPribadi(
            date_time=response['date_time'],
            time=response['time'],
            activity_name=response['activity_name'],
            place_name=response['place_name'],
            category_name=response['category_name']
        )
        formdone.save()
        return HttpResponseRedirect('/ppw5/activity')
    else:
        return HttpResponseRedirect('/ppw5/schedule')

def schedule(request):
    response = {'form': Activity_Form}
    return render(request, 'actform.html', response)

def activity(request):
    result = JadwalPribadi.objects.all()
    response = {'result':result}
    return render(request, 'actformresult.html', response)

def delete(request):
    JadwalPribadi.objects.all().delete()
    return render(request, 'actformresult.html', {})

ppw5/templates/actform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class = "form">
        <h1 class ="title1"><br><br><br>Darin's Personal Agenda <h1>
        <p class = "quotes">The secret of your success determined by your daily agenda. - John C. Maxwell <p>
            <form action="{% url 'ppw5:activity_post' %}" method="POST">
                {% csrf_token %}
                <div class = "row center-block"></div>
                <div class="col-md-4 col-md-offset-4 mx-auto">
                    <div class="form-group">
                        <label for="activity">Activity:</label>
                            {{form.activity_name}}
                        <label for="Location">Location:</label>
                            {{form.place_name}}
                        <label for="date">Date:</label>
                            {{form.date_time}}
                        <label for="activity">Time:</label>
                            {{form.time}}
                        <br><label for="category">Category:</label>
                            {{form.category_name}}
                        </div>
                        <button type="submit" class="btn btn-default btn-block center-block">Add Agenda</button>
                        <br><br>        
                </div>
            </div>
            </form>
    </div>
{% endblock content %}

ppw5/templates/actformresult.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1 class ="title1"><br><br><br>Your Agenda</h1>
{% if result %}
<table class="table">
            <thead class = "quotes">
                <th>Date</th>
                <th>Time</th>
                <th>Activity</th>
                <th>Location</th>
                <th>Category</th>
            </thead>
            <tbody class = "quotes">
                {% for i in result %}
                    <td> {{i.date_time}} </td>
                    <td> {{i.time}} </td>
                    <td> {{i.activity_name}} </td>
                    <td> {{i.place_name}} </td>
                    <td> {{i.category_name}} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
{%else%}
<br>
<p class = "quotes">You don't have any agendas! :D </p>
{% endif %}
        <br><br>
        <div class="col-md-12 butstyle">
            <button type="submit" class="btn btn-default" onclick = "location.href='{% url 'ppw5:empty'%}'">Delete Agenda</button>
            <button type="submit" class="btn btn-default" onclick = "location.href='{% url 'ppw5:schedule'%}'">Add Agenda</button>
        </div>
{% endblock content %}

ppw5/templates/base.html
{% load static %}

<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link href="https://fonts.googleapis.com/css?family=Hind+Vadodara:400,500,700" rel="stylesheet">
            <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
            <title>Darin's Personal Agenda</title>
            <link rel="icon" href="https://cdn1.iconfinder.com/data/icons/banking-and-finance-7-1/128/323-512.png">
        </head>
        <body>
            {% block content %}
            {% endblock content %}
        </body>
    </html>