landingpage/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.landing, name='default'),
    path('welcome/', views.landing, name='welcome'),
]

ppw4/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
]

ppw6/urls.py
from django.urls import path
from .views import *

app_name = 'ppw6'
urlpatterns = [
	path('', profile, name = 'default'),
	path('story/', landing_page, name='how'),
	path('home/', profile, name='profile'),
]

story_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('landingpage.urls')),
    path('admin/', admin.site.urls),
    path('ppw4/', include('ppw4.urls')),
    path('ppw5/', include(('ppw5.urls', 'ppw5'), namespace='ppw5')),
    path('ppw6/', include(('ppw6.urls', 'ppw6'), namespace='ppw6')),
    path('ppw8/', include(('ppw8.urls', 'ppw8'), namespace='ppw8')),
    path('ppw9/', include(('ppw9.urls', 'ppw9'), namespace='ppw9')),
    path('landingpage/', include(('landingpage.urls', 'landingpage'), namespace='landingpage')),
    path('ppw10/', include(('ppw10.urls', 'ppw10'), namespace='ppw10')),
    path('auth/', include('social_django.urls', namespace ='social')),
]

landingpage/models.py
from django.db import models

# Create your models here.

ppw6/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class HowAre(models.Model):
    how_are = models.CharField(max_length = 300)
    submit_time = models.DateTimeField(default=timezone.now())

ppw6/forms.py
from django import forms

class HowAre_Form(forms.Form):
    attrs = {
        'class': 'form-control'
    }
    how_are = forms.CharField(label = '', max_length = 300, required=True, widget=forms.TextInput(attrs=attrs))

landingpage/views.py
from django.shortcuts import render

# Create your views here.
def landing(request):
	return render(request, "awalbgt.html", {})

ppw6/views.py
from django.shortcuts import render, redirect
from .forms import HowAre_Form
from .models import HowAre

# Create your views here.
def landing_page(request):
    form = HowAre_Form(request.POST or None)
    if(request.method == 'POST'):
        result = HowAre.objects.all()
        response = {
            "result" : result
        }
        response['form'] = form
        if(form.is_valid()):
            response['how_are'] = request.POST.get('how_are')
            HowAre.objects.create(how_are=response['how_are'])
            return render(request, 'landingpage.html', response)
        else:
            return render(request, 'landingpage.html', response)
    else:
        result = HowAre.objects.all()
        response = {
            "result" : result
        }
        response['form'] = form
        return render(request, 'landingpage.html', response)

def profile(request):
	return render(request, "profile.html", {})

ppw6/templates/landingpage.html
<!DOCTYPE html>
    <html lang="en" style="height: 100%">
        <head>
            <meta charset="UTF-8">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <title>Your Online Diary</title>
            <link rel="icon" href ="https://cdn0.iconfinder.com/data/icons/love-and-heart-part-2/100/060_-_book-512.png">
        </head>
        <body>
            <div class = "row center-block" style="height: 100vh">
                    <div class="col-md-6 mx-auto" style="background-image: linear-gradient(to right, #ddd6f3, #faaca8);
                        background-size: auto 100%;
                        background-repeat: no-repeat;
                        background-position: left top;
                        background-attachment: fixed; 
                        height: 100%">
                        <br><br><br><br><br><br><br><br>
                        <p style="text-align:center; font-size:3rem"><strong>Hello! How are you?</strong></p>
                        <p style="text-align:center; font-size:1rem">Fill in the form to get lorem ipsum </p>
                        <div class = "form">
                            <form action="{% url 'ppw6:how' %}" method="POST">
                                {% csrf_token %}
                            <div class="form-group">
                                {{form.how_are}}
                                </div>
                                <button type="submit" class="btn btn-default btn-block center-block">Submit</button>
                                </form>
                            </div>
                        </div>
                    <div class="col-md-6" style="background-color:#EBD5D5">
                            <br><br>
                            <div class="card">
                                    <div class="card-header">
                                      <strong>Hi! I am..</strong>
                                    </div>
                                    <div class="card-body">
                                      <blockquote class="blockquote mb-0">
                                        <p>
                                            <table style="width:100%">
                                                {% if result %}
                                                    <!-- <tr>
                                                        <th>Mood</th>
                                                        </tr> -->
                                                            {% for i in result %}
                                                                <tr>
                                                                    <td>{{ i.how_are }}</td>
                                                                    <td>{{ i.submit_time }}</td>
                                                                </tr>
                                                            {% endfor %}
                                                        {% else %}
                                                            <h5> Tell me! :) </h5> 
                                                        {% endif %}
                                                    </table>
                                        </p>
                                      </blockquote>
                                    </div>
                                  </div>
                         </div>
                    </div>
            </div>

        </body>

ppw6/templates/profile.html
<!DOCTYPE html>
    <html lang="en" style="height: 100%">
        <head>
            <meta charset="UTF-8">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <title>Hi!</title>
            <link rel="icon" href ="https://cdn0.iconfinder.com/data/icons/love-and-heart-part-2/100/060_-_book-512.png">
            <style>
                    body{
                        background-image: linear-gradient(to right, #ddd6f3, #faaca8);
                        background-size: auto 100%;
                        background-repeat: no-repeat;
                        background-position: left top;
                        background-attachment: fixed; 
                        height: 100vh;
                    }
                    img{
                        border-radius: 50%
                    }
                </style>
        </head>
        <body>
            <br><br>
        <p style = "text-align: center;"><img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/40854004_512628222566610_6812569312646135808_n.jpg?_nc_cat=0&oh=49e288ae095ece87dd5005e7fdf09617&oe=5C2D9B1B" width="250" height="250"/></p>
        <div style="text-align:center">
                <br>
                <img src = "https://cdn0.iconfinder.com/data/icons/thin-communication-messaging/57/thin-038_comment_chat_message-512.png" width="30" height="30"/><span><strong>darinamandaz@gmail.com</strong></span>
                <img src = "https://cdn3.iconfinder.com/data/icons/web-31/24/phone-circle-512.png"width="30" height="30"/><span><strong>087781958525</strong></span>
                <img src = "https://cdn4.iconfinder.com/data/icons/maps-and-navigation-solid-icons-vol-1/72/19-512.png" width ="30" height="30"/><span><strong>Bintaro, Tangerang Selatan</strong></span>
            </div>
        <div style="text-align:center">
            <br>
            <article>Hello I'm Darin! I am currently a 2nd-year undergraduate student at Faculty of Computer Science, University of Indonesia, majoring in Computer Science. </article>
        </div>
        <div class = "text-center">
        <br><a href = "http://ppw-darina.herokuapp.com/ppw4" class="submit btn btn-primary btn-light">More About Me</a>
        <a href = "http://ppw-darina.herokuapp.com/ppw6/story" class="submit btn btn-primary btn-light">Tell Your Story</a>
        </div>
        <br>
        </body>